src/main/java/com/keunsori/keunsoriserver/member/Member.java, src/main/java/com/keunsori/keunsoriserver/member/MemberRepository.java
- 멤버 엔티티에 hongikgmail 추가했습니다
- 멤버 레포지토리 작성했습니다.
- 멤버 레포지토리는 후에 올라올 signup(회원가입) 서비스와 관련될게 더 많을 듯 싶네요..
close    #7
=> feat: member edited

src/main/java/com/keunsori/keunsoriserver/KeunSoriServerApplication.java, src/main/java/com/keunsori/keunsoriserver/domain/common/BaseEntity.java, src/main/java/com/keunsori/keunsoriserver/domain/member/domain/Member.java, src/main/java/com/keunsori/keunsoriserver/domain/member/domain/vo/MemberStatus.java, src/main/java/com/keunsori/keunsoriserver/domain/member/repository/MemberRepository.java, src/main/java/com/keunsori/keunsoriserver/member/MemberStatus.java
- BaseEntity 작성
- Member 엔티티 approvalDate 필드 추가
- Member 엔티티 BaseEntity 상속
- 패키지 구조 정리
- 실수나 잘못된 것 없는지 확인 한 번 부탁드립니다~~~
close #10
=> feat: Base Entity 작성, Member 엔티티 approvalDate 추가

src/main/java/com/keunsori/keunsoriserver/domain/auth/controller/AuthController.java, src/main/java/com/keunsori/keunsoriserver/domain/auth/login/LoginService.java, src/main/java/com/keunsori/keunsoriserver/domain/auth/login/dto/response/LoginResponse.java
- 프론트와 논의 후 로그인 응답에 이름과 학번을 포함하도록 수정하였습니다.
- 
close #28
=> refactor: Login Response로 멤버 이름과 학번을 반환하도록 개선

.github/workflows/prod-deploy.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml
- 운영 서버 설정 파일과 워크플로우 파일을 작성했습니다.
- 
close #38
=> chore: 운영 서버 설정 추가

src/main/java/com/keunsori/keunsoriserver/global/config/SecurityConfig.java
- 관리자에서 예약쪽 접근 가능하도록 바꿨습니다.
- 나중에 예약 조회만 접근 가능하게 바꿀 수 있으면 좋을 것 같습니다
close #43
=> fix: 관리자 예약조회 허용

src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/request/WeeklyScheduleUpdateRequest.java, src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/response/DailyAvailableResponse.java, src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/response/WeeklyScheduleResponse.java, src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/Reservation.java
- NotBlank -> NotNull로 수정해서 주간 스케줄 저장 시 500에러 뜨는거 해결
- 주간 스케줄, 일간 스케줄 반환 시 시간 포맷 "HH:mm"으로 수정
- 
close #45
=> fix: 주간 스케줄 저장 시 500에러 해결

src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/request/WeeklyScheduleUpdateRequest.java, src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/response/DailyAvailableResponse.java, src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/response/WeeklyScheduleResponse.java, src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/service/AdminReservationService.java, src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/Reservation.java
- 주간스케줄 반환 할때 요일 숫자가 정렬되서 반환되도록 수정했습니다.
- 이거 커밋컨벤션 뭐로 해야할지 헷갈리네요
close #49
=> refactor: 주간스케줄 반환 정렬

src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/validator/ReservationValidator.java, src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/vo/ReservationType.java, src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/vo/Session.java, src/main/java/com/keunsori/keunsoriserver/domain/reservation/repository/ReservationRepository.java, src/main/java/com/keunsori/keunsoriserver/domain/reservation/service/ReservationService.java, src/main/java/com/keunsori/keunsoriserver/global/exception/ErrorMessage.java, src/test/java/com/keunsori/keunsoriserver/reservation/api/ReservationApiTest.java, src/test/java/com/keunsori/keunsoriserver/reservation/domain/ReservationTypeTest.java
- 예약 타입에 교습 타입을 추가하였습니다.
- 
close #50
=> feat: 예약 타입에 교습 타입 추가

src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/response/DailyAvailableResponse.java, src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/response/WeeklyScheduleResponse.java, src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/service/AdminReservationService.java, src/main/java/com/keunsori/keunsoriserver/domain/member/domain/Member.java, src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/Reservation.java, src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/validator/ReservationValidator.java, src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/vo/ReservationType.java, src/main/java/com/keunsori/keunsoriserver/domain/reservation/domain/vo/Session.java, src/main/java/com/keunsori/keunsoriserver/domain/reservation/repository/ReservationRepository.java, src/main/java/com/keunsori/keunsoriserver/domain/reservation/service/ReservationService.java, src/main/java/com/keunsori/keunsoriserver/global/exception/ErrorMessage.java, src/test/java/com/keunsori/keunsoriserver/reservation/api/ReservationApiTest.java, src/test/java/com/keunsori/keunsoriserver/reservation/domain/ReservationTypeTest.java
=> v1.1.0 (2)

src/main/java/com/keunsori/keunsoriserver/global/config/SecurityConfig.java, src/main/java/com/keunsori/keunsoriserver/global/constant/EnvironmentConstant.java
=> feat: 신규 도메인 cors 허용

build.gradle, src/main/java/com/keunsori/keunsoriserver/domain/email/controller/EmailController.java, src/main/java/com/keunsori/keunsoriserver/domain/email/domain/EmailAuthentication.java, src/main/java/com/keunsori/keunsoriserver/domain/email/dto/request/AuthNumberSendRequest.java, src/main/java/com/keunsori/keunsoriserver/domain/email/dto/request/AuthNumberVerifyRequest.java, src/main/java/com/keunsori/keunsoriserver/domain/email/dto/request/EmailValidateRequest.java, src/main/java/com/keunsori/keunsoriserver/domain/email/repository/EmailRepository.java, src/main/java/com/keunsori/keunsoriserver/domain/email/service/EmailService.java, src/main/java/com/keunsori/keunsoriserver/global/config/EmailConfig.java, src/main/java/com/keunsori/keunsoriserver/global/config/RedisConfig.java, src/main/java/com/keunsori/keunsoriserver/global/config/SecurityConfig.java, src/main/java/com/keunsori/keunsoriserver/global/exception/EmailException.java, src/main/java/com/keunsori/keunsoriserver/global/exception/ErrorMessage.java, src/main/java/com/keunsori/keunsoriserver/global/exception/GlobalExceptionHandler.java, src/main/java/com/keunsori/keunsoriserver/global/util/EmailUtil.java, src/main/resources/application-email.yml, src/main/resources/application.yml, src/test/resources/application-test.yml
- 이메일 인증번호 전송
- 이메일 인증번호 검증
- 
close #74
=> feat: 이메일 인증 기능 추가

src/main/java/com/keunsori/keunsoriserver/domain/reservation/service/ReservationService.java
- 그저께 예약가능 테이블 2달치 보내주도록 핫픽스했는데 예약리스트도 똑같이 필요하다해서 예약 리스트 2달치 보내주도록 변경했읍니다.
- 메서드명도 바꿀까말까 고민하다가 일단 올려요
close #81
=> fix: 예약 리스트 2달치 보내주도록 변경

src/main/java/com/keunsori/keunsoriserver/global/constant/EnvironmentConstant.java
- 운영서버 cors url 을 www 없애도록 변경했습니다.
- 
close #93
=> fix: 운영 서버 url 변경

src/main/java/com/keunsori/keunsoriserver/global/config/SecurityConfig.java, src/main/java/com/keunsori/keunsoriserver/global/constant/EnvironmentConstant.java
=> hotfix: update prod front url

src/test/java/com/keunsori/keunsoriserver/admin/member/api/AdminMemberApiTest.java, src/test/java/com/keunsori/keunsoriserver/admin/reservation/api/AdminReservationApiTest.java
- 예약관리 테스트코드 작성
- 회원관리 테스트코드 작성
- 
close #60
=> test: 예약 관리 & 회원관리 테스트 작성

src/main/java/com/keunsori/keunsoriserver/global/config/SecurityConfig.java, src/main/java/com/keunsori/keunsoriserver/global/constant/EnvironmentConstant.java
- localhost https  도메인을 cors 예외에 추가하였습니다.
- 
close #114
=> chore: localhost https cors 예외 추가

src/main/java/com/keunsori/keunsoriserver/global/util/CookieUtil.java
=> refactor: 쿠키에 samesite=none 속성 추가

src/main/java/com/keunsori/keunsoriserver/global/config/SecurityConfig.java, src/main/java/com/keunsori/keunsoriserver/global/constant/EnvironmentConstant.java
=> chore: 사파리 쿠키를 위한 api.keunsori.com cors에 추가

src/main/java/com/keunsori/keunsoriserver/global/properties/SwaggerProperties.java
=> chore: dev profile일 때 Swagger 서버 URL 수정

src/main/java/com/keunsori/keunsoriserver/global/config/SecurityConfig.java, src/main/java/com/keunsori/keunsoriserver/global/constant/EnvironmentConstant.java
=> hotfix: api.dev.keunsori.com 서버 CORS 추가

src/main/java/com/keunsori/keunsoriserver/global/config/SecurityConfig.java, src/main/java/com/keunsori/keunsoriserver/global/config/SwaggerConfig.java, src/main/java/com/keunsori/keunsoriserver/global/constant/EnvironmentConstant.java, src/main/java/com/keunsori/keunsoriserver/global/properties/SwaggerProperties.java
- 스웨거 서버 URL 설정값을 수정했습니다.
- 스웨거 서버 URL 설정값을 기존에 설정한 상수 값에서 가져오도록 하고, SwaggerProperties 는 삭제했습니다.
- 
close #125
=> fix: 스웨거 개발서버 url 설정 수정

src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/domain/validator/RegularReservationValidator.java, src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/request/WeeklyScheduleManagementRequest.java, src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/dto/response/RegularReservationResponse.java, src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/repository/RegularReservationRepository.java, src/main/java/com/keunsori/keunsoriserver/domain/admin/reservation/service/AdminReservationService.java, src/main/java/com/keunsori/keunsoriserver/global/exception/ErrorMessage.java
- 정기 예약 repository query문 수정
- 주간 스케줄 GET에서 필요없는 응답 필드 TeamLeaderId 삭제
- 
close #136
=> hotfix: 정기 예약 레포지토리 query문 수정
